### ISSUE TITLE
action "add" causes TypeError

### ISSUE THREAD

**Issue by regioadmin** [NerLOR/World4YouApi#3]
I get "TypeError: 'builtin_function_or_method' object is not subscriptable" when adding an entry. Updating entries works fine.
I'm on python 3.8. What's wrong?
```
python3.8 world4you  -u000000 -p00000 add _acme-challenge.test.mydomain.com TXT 12345678
Successfully logged in

Traceback (most recent call last):
  File "world4you", line 199, in <module>
    if not add(*args.arg):
  File "world4you", line 24, in add
    return api.add_resource_record(record_type, record_name, record_value)
  File "/root/W4YOU_DNS_API/World4YouApi.py", line 280, in add_resource_record
    'AddDnsRecordForm[name]': fqdn.split[:-len(package.domain) - 1],
TypeError: 'builtin_function_or_method' object is not subscriptable
```

**Comment by astnerdev** [comment]
@regioadmin Had the same error I created a pull request https://github.com/NerLOR/World4YouApi/pull/2
You must wait for the maintainer to accept the pull request or pull my fork. https://github.com/mastox/World4YouApi

**Comment by regioadmin** [comment]
Thx  for your fork!
There is another issue with "add - command". It drops subdomains.
e.g command: `world4you  -uxxxx -pxxxx  add  _acme-challenge.subdomain.example.com TXT blablabla`
creates  DNS   **example.com  TXT blablabla**
_acme... is dropped.

**Comment by astnerdev** [comment]
@regioadmin you were right, i pushed the changes.
i tried with `world4you -uxxxx -pxxxx add _acme-challenge.subdomain.example.com TXT blablabla` 
and 
`world4you -uxxxx -pxxxx add _acme-challenge.example.com TXT blablabla`

and both worked for me.
