### ISSUE TITLE
error: unrecognized arguments: -f

### ISSUE THREAD

**Issue by muj85** [NerLOR/World4YouApi#5]
Hi,
using latest version (93b08ffc35f51c60417dde294a74e10ee417affb), option -f is not available ...

usage: world4you [-h] [-i] [-q] -u username [-p pwd] [-P file] [action] [arg ...]
world4you: error: unrecognized arguments: -f

README says:

-f, --force-one If the provided FQDN-Type-Value combination is not unique, perform the specified action on exactly one matching resource record

Thank you and BR

**Comment by NerLOR** [comment]
Fixed. See 0870d20
